const axios = require("axios");
const fs = require("fs");
const path = require("path");

module.exports = {
  name: "image",
  version: "3.0",
  hasPrefix: false,
  description: "Generate AI images using Pollinations or Lexica as fallback",
  usage: "image <prompt>",
  credits: "Jonnel Soriano",

  async execute({ api, event, args }) {
    const { threadID, messageID } = event;

    if (!args.length) {
      return api.sendMessage("🖼️ Usage: image <prompt>\nExample: image red cat", threadID, messageID);
    }

    const prompt = args.join(" ");
    const tempPath = path.join(__dirname, "generated_image.jpg");

    // Format Date & Time
    const now = new Date();
    const time = now.toLocaleTimeString("en-PH", { hour12: true });
    const date = now.toLocaleDateString("en-PH");

    // Default to Pollinations AI
    let imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`;
    let source = "Pollinations AI";

    api.setMessageReaction("🎨", messageID, () => {}, true);
    api.sendMessage(`🎨 Generating image for: "${prompt}"... please wait.`, threadID, messageID);

    try {
      // Try Pollinations
      const img = await axios.get(imageUrl, { responseType: "arraybuffer" });
      fs.writeFileSync(tempPath, img.data);

      const msg = `🟢⚪🔴 𝗔𝗜 𝗜𝗠𝗔𝗚𝗘 𝗚𝗘𝗡𝗘𝗥𝗔𝗧𝗢𝗥 🟢⚪🔴

🖼️ *Prompt:* ${prompt}
🔗 *Source:* ${source}
👨‍💻 *Creator:* Jonnel Soriano
🕒 *Time:* ${time}
📅 *Date:* ${date}

━━━━━━━━━━━━━━━
✅ Successfully generated by ${source}!`;

      return api.sendMessage(
        { body: msg, attachment: fs.createReadStream(tempPath) },
        threadID,
        () => {
          fs.unlinkSync(tempPath);
          api.setMessageReaction("✅", messageID, () => {}, true);
        }
      );

    } catch (error) {
      console.warn("⚠️ Pollinations failed, switching to Lexica:", error.message);
    }

    // Fallback to Lexica.art
    try {
      const lexica = await axios.get(`https://lexica.art/api/v1/search?q=${encodeURIComponent(prompt)}`);
      if (lexica.data && lexica.data.images && lexica.data.images.length > 0) {
        imageUrl = lexica.data.images[0].src;
        source = "Lexica.art";

        const img = await axios.get(imageUrl, { responseType: "arraybuffer" });
        fs.writeFileSync(tempPath, img.data);

        const msg = `🟢⚪🔴 𝗔𝗜 𝗜𝗠𝗔𝗚𝗘 𝗚𝗘𝗡𝗘𝗥𝗔𝗧𝗢𝗥 🟢⚪🔴

🖼️ *Prompt:* ${prompt}
🔗 *Source:* ${source}
👨‍💻 *Creator:* Jonnel Soriano
🕒 *Time:* ${time}
📅 *Date:* ${date}

━━━━━━━━━━━━━━━
✅ Image fetched from ${source}!`;

        return api.sendMessage(
          { body: msg, attachment: fs.createReadStream(tempPath) },
          threadID,
          () => {
            fs.unlinkSync(tempPath);
            api.setMessageReaction("✅", messageID, () => {}, true);
          }
        );
      } else {
        throw new Error("No image found in Lexica");
      }
    } catch (err) {
      console.error("❌ All sources failed:", err.message);
      api.sendMessage(
        `❌ Sorry, no image was generated.\nTry another prompt.\n\n🟢⚪🔴 *Creator:* Jonnel Soriano`,
        threadID,
        messageID
      );
      api.setMessageReaction("❌", messageID, () => {}, true);
    }
  }
};